#!/usr/bin/env bash

if ! command -v fish &>/dev/null; then
	echo "ERR: Install fish"
	exit 1
fi

if ! command -v syncthing &>/dev/null; then
	echo "ERR: Install syncthing"
	exit 1
fi

if ! command -v paru &>/dev/null; then
	echo "ERR: Install paru"
	exit 1
fi

if ! test -d ./ssh; then
	echo "ERR: no ssh config present. use syncthing to transfer your ssh config"
	exit 1
fi

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
