#!/bin/bash

CF=$HOME/.config/waybar/config.jsonc
CONFIG_FILES="$CF $HOME/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
	hyperctl dispatch exec waybar --config $CF
	inotifywait -e create,modify $CONFIG_FILES
	killall waybar
done
