#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

pkill compton 
pkill picom 
pkill polybar
pkill dunst
pkill lxsession
pkill polkit-gnome-authentication-agent-1
pkill xfce4-power-manager
pkill syncthing
pkill devilspie
# pkill conky
pkill pnmixer
pkill blueberry-tray
pkill xidlehook
